### ISSUE TITLE
版本太高了呀

### ISSUE THREAD

**Issue by gitlsl** [huoshan12345/iQQ.Net#1]
建议 降低版本到 4.0    不要用vs2015的c# 新语法  这样  vs2010  这些还能打开~。。

**Comment by huoshan12345** [comment]
我反而建议你升级vs2015，如果用xp赶紧升级系统吧
mono都不支持.net4.0了
最要命的是4.0不支持async/await，不能忍= =

**Comment by gitlsl** [comment]
4.0 支持async/await 的。。  主要是你用了vs2015 的语法糖    这样低于2015的vs都打不开了

**Comment by jijiechen** [comment]
开发工具还是建议要用最新的 @gitlsl
